=== shruthi-07-goud/EWP-WEEK-6/menu.dtd
<!ELEMENT menu (item+)>

<!ELEMENT item (name, category, type, price)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== shruthi-07-goud/EWP-WEEK-6/menu.xml
<?xml version="1.0"?>
<!DOCTYPE menu SYSTEM "menu.dtd">

<menu>

    <item>
        <name>Cappuccino</name>
        <category>Coffee</category>
        <type>Hot Beverage</type>
        <price>149</price>
    </item>

    <item>
        <name>Cold Coffee</name>
        <category>Coffee</category>
        <type>Cold Beverage</type>
        <price>129</price>
    </item>

    <item>
        <name>Chocolate Cake</name>
        <category>Dessert</category>
        <type>Cake</type>
        <price>199</price>
    </item>

    <item>
        <name>Veg Sandwich</name>
        <category>Snacks</category>
        <type>Sandwich</type>
        <price>149</price>
    </item>

    <item>
        <name>French Fries</name>
        <category>Snacks</category>
        <type>Fast Food</type>
        <price>119</price>
    </item>

</menu>
